name: CCflow bulid
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
    - name: dotnet env construction
      run: |
        sudo su
        sudo apt-get update
        sudo apt-get install -y wget
        sudo wget https://packages.microsoft.com/config/ubuntu/20.10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo rm packages-microsoft-prod.deb
        sudo apt-get install -y apt-transport-https
        sudo apt-get install -y dotnet-sdk-3.1
        sudo mkdir -p /root/.nuget/packages
    - name: ccflow build
      run: |
        sudo cp -r /home/runner/work/CCFlow/CCFlow/packages/pdflib_dotnet /root/.nuget/packages
        sudo rm -fr /home/runner/work/CCFlow/CCFlow/CCFlow/bin
        sudo rm -fr /home/runner/work/CCFlow/CCFlow/CCFlow/obj
        sudo dotnet build /home/runner/work/CCFlow/CCFlow/CCFlow
        sudo ls /home/runner/work/CCFlow/CCFlow/CCFlow/bin/Debug/netcoreapp3.1
        
